use std::path::{Path, PathBuf};

use musubi_reference_readers::absence::GapBounds;
use musubi_reference_readers::cause::negative_digest;
use musubi_reference_readers::eval::{Metrics, top_candidate};
use musubi_reference_types::{
    CauseCandidate, CauseOutcome, ChannelId, ClockBasis, DigestRef, LogicConfidence, MarkStatus,
    NegativeObservation,
};

use crate::timefmt::{iso_utc_ms, pm_s, rel_s};
use crate::{Knowledge, PipelineOut, SourceRun, WALL_MAPPED};

pub const NOTE_CANDIDATE: &str = "candidate, not a verdict";
pub const NOTE_CEILING: &str = "Synthetic records generated by KECKU from public format specs; this shows the mechanism on synthetic records and proves nothing about any partner's files.";
pub const QUESTION_7: &str = "Where is a gap in the system, and what most likely caused it (a severed fibre-optic link, a failed controller, a camera that stopped)?";

pub const EXPORT_SCHEMA_VERSION: &str = "3";

pub const CANDIDATE_SELECTION_RULE: &str = "display-derived:eval::top_candidate@1";

pub const EVIDENCE_DIGESTS_HEAD: usize = 8;

#[must_use]
pub const fn mark_label(s: MarkStatus) -> &'static str {
    match s {
        MarkStatus::Ok => "ok",
        MarkStatus::Degraded => "degraded",
        MarkStatus::Invalid => "invalid",
        MarkStatus::OrderUnknown => "order_unknown",
        MarkStatus::Withheld => "withheld",
        MarkStatus::StaleRevocation => "stale_revocation",
        MarkStatus::SelfAssertedTime => "self_asserted_time",
        MarkStatus::BufferSaturated => "buffer_saturated",
    }
}

fn csv_field(s: &str) -> String {
    if s.contains(',') || s.contains('"') || s.contains('\n') {
        format!("\"{}\"", s.replace('"', "\"\""))
    } else {
        s.to_string()
    }
}

fn row(fields: &[String]) -> String {
    let mut s = fields
        .iter()
        .map(|f| csv_field(f))
        .collect::<Vec<_>>()
        .join(",");
    s.push('\n');
    s
}

#[must_use]
pub fn digest_hex8(d: &DigestRef) -> String {
    d.0.iter().take(8).map(|b| format!("{b:02x}")).collect()
}

pub const DIGEST_PREFIX: &str = "sha256:";

#[must_use]
pub fn digest_cell(d: &DigestRef) -> String {
    format!("{DIGEST_PREFIX}{}", digest_hex8(d))
}

#[must_use]
pub fn digest_full_cell(d: &DigestRef) -> String {
    let hex: String = d.0.iter().map(|b| format!("{b:02x}")).collect();
    format!("{DIGEST_PREFIX}{hex}")
}

fn join_channels(v: &[ChannelId]) -> String {
    v.iter().map(|c| c.as_str()).collect::<Vec<_>>().join("|")
}

#[must_use]
pub const fn clock_caption(b: ClockBasis) -> &'static str {
    match b {
        ClockBasis::GpsLocked => "GNSS-derived UTC (absolute)",
        ClockBasis::GpsSuspect => "GNSS time, suspect (interference/inconsistency signs)",
        ClockBasis::RtcSetOnce => {
            "clock set once at boot (device-internal afterwards; tz per device)"
        }
        ClockBasis::BootRelativeOffsetEstimated => "boot-relative + estimated offset",
        ClockBasis::HostReceived => "ground-side receive time (not the vehicle's clock)",
        ClockBasis::BootRelative => "boot-relative only (absolute time unknown)",
        ClockBasis::Unknown => "time unknown (file-system time / epoch 0)",
    }
}

#[must_use]
pub fn source_clock_line(s: &SourceRun) -> String {
    let al = &s.alignment;
    let mut line = format!("{} — {}", al.basis.as_label(), clock_caption(al.basis));
    if let Some(o) = al.offset.filter(|_| !s.host_axis()) {
        line.push_str(&format!(
            " (boot 0 ≈ {} UTC {}, source {}, anchors {}{})",
            iso_utc_ms(o.offset_us / 1000),
            pm_s(o.bound_us / 1000),
            o.source.as_label(),
            o.anchors,
            if o.discontinuity {
                ", discontinuity"
            } else {
                ""
            }
        ));
    }
    line
}

#[must_use]
pub fn absences_csv(out: &PipelineOut) -> String {
    let mut s = String::from(
        "family,asset_id,source_role,profile_id,profile_origin,file,channel,expectation_id,absent_since_utc,absent_since_wall_ms,expected_by_wall_ms,wall_bound_ms,absent_since_native_ms,expected_by_native_ms,clock_basis,time_confidence_min,last_good_digest,mark_status,mark_reason,note,absence_digest,export_schema_version,absence_digest_full,last_good_digest_full,gap_end,next_good_native_ms,next_good_clock_basis,next_good_digest,next_good_digest_full,wall_mapping\n",
    );
    for n in &out.noticed {
        s.push_str(&row(&absence_row(
            source_for(out, &n.asset_id, n.source_index),
            &n.negative,
            n.bounds,
            Some((n.since_wall_ms, n.by_wall_ms, n.bound_ms)),
            WALL_MAPPED,
        )));
    }
    for u in &out.unmapped {
        s.push_str(&row(&absence_row(
            source_for(out, &u.asset_id, u.source_index),
            &u.negative,
            u.bounds,
            None,
            u.reason,
        )));
    }
    s
}

pub const WALL_UNMAPPED_UNKNOWN_CLOCK: &str = "unmapped_unknown_clock";

fn absence_row(
    src: Option<&SourceRun>,
    neg: &NegativeObservation,
    bounds: GapBounds,
    wall: Option<(i64, i64, i64)>,
    mapping: &str,
) -> Vec<String> {
    let unknown_clock = neg.clock_basis == ClockBasis::Unknown;
    let mapping = if unknown_clock {
        WALL_UNMAPPED_UNKNOWN_CLOCK
    } else {
        mapping
    };
    let wall = if unknown_clock { None } else { wall };
    let (since_utc, since_wall, by_wall, bound) = wall.map_or_else(
        || (String::new(), String::new(), String::new(), String::new()),
        |(since, by, bound)| {
            (
                iso_utc_ms(since),
                since.to_string(),
                by.to_string(),
                bound.to_string(),
            )
        },
    );
    vec![
        neg.subject.family.as_str().into(),
        neg.subject.asset_id.clone(),
        src.map_or("?".into(), |x| x.profile.source_role.as_str().to_string()),
        src.map_or("?".into(), |x| x.profile.profile_id.clone()),
        src.map_or("?".into(), |x| x.profile.origin.clone()),
        src.map_or("?".into(), |x| x.file_name.clone()),
        neg.subject.channel.as_str().into(),
        neg.expectation_id.clone(),
        since_utc,
        since_wall,
        by_wall,
        bound,
        neg.absent_since_ms.to_string(),
        neg.expected_by_ms.to_string(),
        neg.clock_basis.as_label().into(),
        format!("{:.2}", neg.time_confidence_min),
        neg.last_good
            .as_ref()
            .map_or("never-observed".into(), digest_cell),
        mark_label(neg.mark.status).into(),
        neg.mark.reason_code.clone(),
        "absence = Musubi says it is missing; not 'no data'".into(),
        digest_cell(&negative_digest(neg)),
        EXPORT_SCHEMA_VERSION.into(),
        digest_full_cell(&negative_digest(neg)),
        neg.last_good
            .as_ref()
            .map_or("never-observed".into(), digest_full_cell),
        bounds.end.as_label().into(),
        bounds
            .next_good_ms
            .map_or_else(String::new, |v| v.to_string()),
        bounds
            .next_good_clock_basis
            .map_or_else(String::new, |b| b.as_label().to_string()),
        bounds
            .next_good
            .as_ref()
            .map_or("open-end".into(), digest_cell),
        bounds
            .next_good
            .as_ref()
            .map_or("open-end".into(), digest_full_cell),
        mapping.into(),
    ]
}

fn source_for<'a>(
    out: &'a PipelineOut,
    asset_id: &str,
    source_index: usize,
) -> Option<&'a SourceRun> {
    out.assets
        .iter()
        .find(|a| a.asset_id == asset_id)
        .and_then(|a| a.sources.get(source_index))
}

#[must_use]
pub fn candidate_line(c: &CauseCandidate) -> String {
    format!(
        "{} [{}, {}/{} cues, {} contradicting]",
        c.signature_id,
        c.logic_confidence.as_label(),
        c.signature_match.matched_cues.len(),
        c.signature_match.required_cues.len(),
        c.signature_match.contradicting_cues.len()
    )
}

#[must_use]
pub fn consistent_with(k: &Knowledge, signature_id: &str) -> String {
    k.catalog
        .signatures
        .iter()
        .find(|s| s.signature_id == signature_id)
        .map_or_else(|| signature_id.to_string(), |s| s.consistent_with.clone())
}

#[must_use]
pub fn outcome_lines(k: &Knowledge, o: &CauseOutcome) -> (String, String, String, String) {
    match o {
        CauseOutcome::Consistent { candidates } => {
            let top = top_candidate(o).map(|(id, _, _)| id).unwrap_or_default();
            let main =
                candidates
                    .iter()
                    .find(|c| c.signature_id == top)
                    .map_or(String::new(), |c| {
                        format!(
                            "{} — {}",
                            consistent_with(k, &c.signature_id),
                            candidate_line(c)
                        )
                    });
            let alts: Vec<String> = candidates
                .iter()
                .filter(|c| c.signature_id != top)
                .map(candidate_line)
                .collect();
            let alt = if alts.is_empty() {
                "none (all discriminating cues observed)".to_string()
            } else {
                alts.join("; ")
            };
            let missing: Vec<String> = candidates
                .iter()
                .flat_map(|c| c.discriminating_missing.iter().cloned())
                .collect();
            (
                "consistent".into(),
                main,
                alt,
                if missing.is_empty() {
                    "nothing further required".into()
                } else {
                    dedup(missing).join("; ")
                },
            )
        }
        CauseOutcome::Ambiguous {
            candidates,
            indistinguishable_by,
        } => {
            let names: Vec<String> = candidates.iter().map(candidate_line).collect();
            let missing: Vec<String> = candidates
                .iter()
                .flat_map(|c| c.discriminating_missing.iter().cloned())
                .collect();
            (
                "ambiguous".into(),
                format!("ambiguous between: {}", names.join(" / ")),
                "candidates shown in parallel (no ranking)".into(),
                format!(
                    "would disambiguate: {}{}",
                    if indistinguishable_by.is_empty() {
                        "-".to_string()
                    } else {
                        indistinguishable_by.join("|")
                    },
                    if missing.is_empty() {
                        String::new()
                    } else {
                        format!("; missing: {}", dedup(missing).join("; "))
                    }
                ),
            )
        }
        CauseOutcome::Unknown { reason } => (
            "unknown".into(),
            format!("unknown ({})", reason.as_label()),
            "none".into(),
            match reason {
                musubi_reference_types::UnknownReason::ChannelNotObserved => {
                    "a channel required by every signature is not observed in this profile set"
                        .into()
                }
                musubi_reference_types::UnknownReason::NoSignatureMatch => {
                    "no catalog signature matches the observed cues".into()
                }
                musubi_reference_types::UnknownReason::InsufficientEvidence => {
                    "silence confirmed; no evidence narrows the cause".into()
                }
                musubi_reference_types::UnknownReason::TimeUntrusted => {
                    "time anchors are degraded; ordering is not claimed".into()
                }
                musubi_reference_types::UnknownReason::SelfLivenessLost => {
                    "Musubi's own liveness was lost; not attributed to the source".into()
                }
            },
        ),
    }
}

fn dedup(mut v: Vec<String>) -> Vec<String> {
    v.sort();
    v.dedup();
    v
}

#[must_use]
pub fn claims_csv(out: &PipelineOut, k: &Knowledge) -> String {
    let mut s = String::from(
        "claim_id,family,asset_id,trigger_channel,window_start_utc,window_start_ms,window_end_ms,outcome,unknown_reason,candidate_signature,consistent_with,logic_confidence,match_cues_matched,match_cues_required,match_contradicting,alternatives,indistinguishable_by,what_would_disambiguate,channel_coverage_present,channel_coverage_required,input_min_confidence,basis_mix_adapter,basis_mix_measured,basis_mix_unspecified,time_confidence_min,clock_basis,time_untrusted,absence_refs,evidence_count,evidence_digests_head,catalog_version,profile_versions,build_id,mark_status,mark_reason,note,candidate_selection_rule,absence_digests,export_schema_version,absence_digests_full,evidence_digests_full\n",
    );
    for c in &out.claims {
        let cl = &c.claim;
        let (state, _main, alt, missing) = outcome_lines(k, &cl.outcome);
        let (top_id, cand) = match &cl.outcome {
            CauseOutcome::Consistent { candidates } => {
                let id = top_candidate(&cl.outcome)
                    .map(|(id, _, _)| id)
                    .unwrap_or_default();
                let c = candidates.iter().find(|x| x.signature_id == id);
                (id, c)
            }
            CauseOutcome::Ambiguous { .. } | CauseOutcome::Unknown { .. } => (String::new(), None),
        };
        let unknown_reason = match &cl.outcome {
            CauseOutcome::Unknown { reason } => reason.as_label().to_string(),
            _ => String::new(),
        };
        let indist = match &cl.outcome {
            CauseOutcome::Ambiguous {
                indistinguishable_by,
                ..
            } => indistinguishable_by.join("|"),
            _ => String::new(),
        };
        let clock = cl
            .mark
            .reason_code
            .split('|')
            .find_map(|t| t.strip_prefix("clock-basis:"))
            .unwrap_or("")
            .to_string();
        let ev: Vec<String> = cl
            .evidence
            .iter()
            .take(EVIDENCE_DIGESTS_HEAD)
            .map(digest_cell)
            .collect();
        s.push_str(&row(&[
            cl.claim_id.clone(),
            cl.subject.family.as_str().into(),
            cl.subject.asset_id.clone(),
            cl.subject.channel.as_str().into(),
            iso_utc_ms(c.window_start_ms),
            c.window_start_ms.to_string(),
            c.window_end_ms.to_string(),
            state,
            unknown_reason,
            top_id.clone(),
            if top_id.is_empty() {
                String::new()
            } else {
                consistent_with(k, &top_id)
            },
            match &cl.outcome {
                CauseOutcome::Consistent { .. } => cand
                    .map_or(LogicConfidence::NoBasis.as_label().to_string(), |x| {
                        x.logic_confidence.as_label().to_string()
                    }),
                CauseOutcome::Ambiguous { .. } => "per-candidate (see alternatives)".to_string(),
                CauseOutcome::Unknown { .. } => LogicConfidence::NoBasis.as_label().to_string(),
            },
            cand.map_or(String::new(), |x| {
                x.signature_match.matched_cues.len().to_string()
            }),
            cand.map_or(String::new(), |x| {
                x.signature_match.required_cues.len().to_string()
            }),
            cand.map_or(String::new(), |x| {
                x.signature_match.contradicting_cues.len().to_string()
            }),
            alt,
            indist,
            missing,
            join_channels(&cl.input_confidence.channel_coverage.present),
            join_channels(&cl.input_confidence.channel_coverage.required),
            format!("{:.2}", cl.input_confidence.min_confidence),
            cl.input_confidence.basis_mix.adapter_assigned.to_string(),
            cl.input_confidence.basis_mix.measured.to_string(),
            cl.input_confidence.basis_mix.unspecified.to_string(),
            format!("{:.2}", cl.input_confidence.time_confidence_min),
            clock,
            cl.mark
                .reason_code
                .split('|')
                .any(|t| t == "time-untrusted")
                .to_string(),
            cl.absence.len().to_string(),
            cl.evidence.len().to_string(),
            ev.join("|"),
            cl.generator.catalog_version.clone(),
            cl.generator.profile_version.replace(',', "|"),
            cl.generator.build_id.clone(),
            mark_label(cl.mark.status).into(),
            cl.mark.reason_code.clone(),
            NOTE_CANDIDATE.into(),
            CANDIDATE_SELECTION_RULE.into(),
            cl.absence
                .iter()
                .map(digest_cell)
                .collect::<Vec<_>>()
                .join("|"),
            EXPORT_SCHEMA_VERSION.into(),
            cl.absence
                .iter()
                .map(digest_full_cell)
                .collect::<Vec<_>>()
                .join("|"),
            cl.evidence
                .iter()
                .map(digest_full_cell)
                .collect::<Vec<_>>()
                .join("|"),
        ]));
    }
    s
}

#[must_use]
pub fn claim_lines(out: &PipelineOut, k: &Knowledge, idx: usize) -> Vec<String> {
    let Some(c) = out.claims.get(idx) else {
        return Vec::new();
    };
    let cl = &c.claim;
    let (state, main, alt, missing) = outcome_lines(k, &cl.outcome);
    let mut v = vec![
        format!(
            "{} ({}) · window {} -> {} ({} from start) · trigger {}",
            cl.subject.asset_id,
            cl.subject.family.as_str(),
            iso_utc_ms(c.window_start_ms),
            iso_utc_ms(c.window_end_ms),
            rel_s(c.window_start_ms - out.t0_ms),
            cl.subject.channel.as_str()
        ),
        format!("outcome: {state} — {NOTE_CANDIDATE}"),
        format!("most consistent: {main}"),
        format!("alternatives: {alt}"),
        format!("what would disambiguate / missing: {missing}"),
        format!(
            "logic confidence (ladder): {}",
            match &cl.outcome {
                CauseOutcome::Consistent { .. } => top_candidate(&cl.outcome)
                    .map_or("no_basis".to_string(), |(_, l, _)| l.as_label().to_string()),
                CauseOutcome::Ambiguous { .. } =>
                    "per candidate, no ranking (see below)".to_string(),
                CauseOutcome::Unknown { .. } => "no_basis".to_string(),
            }
        ),
        format!(
            "input confidence (reference only): required channels present {}/{} [{}] · Claim.confidence min {:.2} · basis adapter/measured/unspecified {}/{}/{} · time_confidence min {:.2}",
            cl.input_confidence.channel_coverage.present.len(),
            cl.input_confidence.channel_coverage.required.len(),
            join_channels(&cl.input_confidence.channel_coverage.present),
            cl.input_confidence.min_confidence,
            cl.input_confidence.basis_mix.adapter_assigned,
            cl.input_confidence.basis_mix.measured,
            cl.input_confidence.basis_mix.unspecified,
            cl.input_confidence.time_confidence_min
        ),
        format!(
            "mark: {:?} {} · absence refs {} · evidence {} [{}]",
            cl.mark.status,
            cl.mark.reason_code,
            cl.absence.len(),
            cl.evidence.len(),
            cl.evidence
                .iter()
                .take(4)
                .map(digest_hex8)
                .collect::<Vec<_>>()
                .join(" ")
        ),
        format!(
            "generator: catalog {} · profiles {} · {}",
            cl.generator.catalog_version, cl.generator.profile_version, cl.generator.build_id
        ),
    ];
    if let CauseOutcome::Consistent { candidates } | CauseOutcome::Ambiguous { candidates, .. } =
        &cl.outcome
    {
        for cand in candidates {
            v.push(format!(
                "  · {} — matched [{}] optional [{}] contradicting [{}] missing-to-discriminate [{}]",
                candidate_line(cand),
                cand.signature_match.matched_cues.join(", "),
                cand.signature_match.optional_cues_matched.join(", "),
                cand.signature_match.contradicting_cues.join(", "),
                cand.discriminating_missing.join(", ")
            ));
        }
    }
    v
}

#[must_use]
pub fn stand_in_line(
    asset_id: &str,
    family: musubi_reference_types::Family,
    s: &SourceRun,
) -> String {
    let tag = if s.profile.origin == "public" {
        "STAND-IN: KECKU public default profile (our assumption, not the partner's)"
    } else {
        "partner-supplied profile"
    };
    format!(
        "{} ({}) · {} · {} — {}",
        asset_id,
        family.as_str(),
        s.profile.source_role.as_str(),
        s.profile.profile_id,
        tag
    )
}

#[must_use]
pub fn stand_in_lines(out: &PipelineOut) -> Vec<String> {
    out.assets
        .iter()
        .flat_map(|a| {
            a.sources
                .iter()
                .map(move |s| stand_in_line(&a.asset_id, a.family, s))
        })
        .collect()
}

#[must_use]
pub fn answer_paragraph(out: &PipelineOut) -> String {
    let families: Vec<&str> = {
        let mut f: Vec<&str> = out.assets.iter().map(|a| a.family.as_str()).collect();
        f.sort_unstable();
        f.dedup();
        f
    };
    let n_unknown = out
        .claims
        .iter()
        .filter(|c| matches!(c.claim.outcome, CauseOutcome::Unknown { .. }))
        .count();
    let n_amb = out
        .claims
        .iter()
        .filter(|c| matches!(c.claim.outcome, CauseOutcome::Ambiguous { .. }))
        .count();
    let n_cons = out.claims.len() - n_amb - n_unknown;
    let n_cons_with_alt = out
        .claims
        .iter()
        .filter(|c| matches!(&c.claim.outcome, CauseOutcome::Consistent { candidates } if candidates.len() > 1))
        .count();
    format!(
        "Across {} assets in {} families ({}), read from {} record files on one shared time axis (ground-side receive time; vehicle clocks are boot-relative and shown with an estimated offset and error band), Musubi noticed {} gaps (absences against each profile's expected cadence) and opened {} analysis windows. For {} of them the observed cues are consistent with a catalog signature (the most consistent one is shown first; {} of these also list alternatives), {} are ambiguous between several (shown in parallel, no ranking, with what would tell them apart), and {} are unknown with a stated reason. Every cause below is a candidate produced by deterministic signature matching — not a verdict — and each line says which channels were missing that would have narrowed it further.",
        out.assets.len(),
        families.len(),
        families.join("/"),
        out.files.len(),
        out.noticed.len(),
        out.claims.len(),
        n_cons,
        n_cons_with_alt,
        n_amb,
        n_unknown
    )
}

#[must_use]
pub fn answer_text(out: &PipelineOut, k: &Knowledge, metrics: Option<&Metrics>) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "Question 7: {QUESTION_7}

"
    ));
    s.push_str(&format!(
        "Answer (one paragraph): {}

",
        answer_paragraph(out)
    ));
    s.push_str(
        "Where and what (per analysis window):
",
    );
    for (i, c) in out.claims.iter().enumerate() {
        let (state, main, alt, missing) = outcome_lines(k, &c.claim.outcome);
        let absent: Vec<String> = out
            .noticed
            .iter()
            .filter(|n| {
                n.asset_id == c.asset_id
                    && n.since_wall_ms >= c.window_start_ms
                    && n.since_wall_ms < c.window_end_ms
            })
            .map(|n| {
                format!(
                    "{} absent since {} ({} {})",
                    n.negative.subject.channel.as_str(),
                    iso_utc_ms(n.since_wall_ms),
                    n.negative.clock_basis.as_label(),
                    pm_s(n.bound_ms)
                )
            })
            .collect();
        s.push_str(&format!(
            "  {}. {} ({}) @ {} ({}): gaps [{}] -> {}: {} | alternatives: {} | would disambiguate: {}\n",
            i + 1,
            c.asset_id,
            c.claim.subject.family.as_str(),
            iso_utc_ms(c.window_start_ms),
            rel_s(c.window_start_ms - out.t0_ms),
            if absent.is_empty() {
                "event-triggered, no absence".to_string()
            } else {
                absent.join("; ")
            },
            state,
            main,
            alt,
            missing
        ));
    }
    if out.claims.is_empty() {
        s.push_str("  (no gap or triggering event in these records)\n");
    }
    s.push_str("\nClock assumptions per record (recorded clock model):\n");
    for a in &out.assets {
        for src in &a.sources {
            s.push_str(&format!(
                "  {} · {} · {} [{}]: {}\n",
                a.asset_id,
                src.profile.source_role.as_str(),
                src.profile.profile_id,
                src.profile.origin,
                source_clock_line(src)
            ));
        }
    }
    s.push_str("  Shared axis = host receive time + estimated offset; absence is judged on each record's own axis; ordering across records is claimed only when error bands do not overlap (otherwise ORDER_UNKNOWN).\n");
    s.push_str("\nStand-in / assumptions:\n");
    for l in stand_in_lines(out) {
        s.push_str(&format!("  {l}\n"));
    }
    s.push_str(&format!("\nClaim ceiling: {NOTE_CEILING}\n"));
    if let Some(m) = metrics {
        s.push_str(&format!(
            "\nReference metrics against the synthetic ground truth (numbers only, no pass/fail threshold):\n  {}\n",
            m.summary()
        ));
    }
    s
}

pub fn export_all(
    out: &PipelineOut,
    k: &Knowledge,
    metrics: Option<&Metrics>,
    dir: &Path,
) -> std::io::Result<Vec<PathBuf>> {
    std::fs::create_dir_all(dir)?;
    let mut written = Vec::new();
    let a = dir.join("absences.csv");
    std::fs::write(&a, absences_csv(out))?;
    written.push(a);
    let c = dir.join("cause_claims.csv");
    std::fs::write(&c, claims_csv(out, k))?;
    written.push(c);
    let t = dir.join("answer.txt");
    std::fs::write(&t, answer_text(out, k, metrics))?;
    written.push(t);
    if let Some(m) = metrics {
        let p = dir.join("metrics.txt");
        std::fs::write(&p, format!("{}\n{}", m.summary(), m.detail_block()))?;
        written.push(p);
    }
    Ok(written)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn csv_fields_are_quoted_only_when_needed() {
        assert_eq!(csv_field("plain"), "plain");
        assert_eq!(csv_field("a,b"), "\"a,b\"");
        assert_eq!(csv_field("say \"hi\""), "\"say \"\"hi\"\"\"");
    }

    #[test]
    fn clock_captions_cover_every_basis() {
        for b in [
            ClockBasis::GpsLocked,
            ClockBasis::GpsSuspect,
            ClockBasis::RtcSetOnce,
            ClockBasis::BootRelativeOffsetEstimated,
            ClockBasis::HostReceived,
            ClockBasis::BootRelative,
            ClockBasis::Unknown,
        ] {
            assert!(!clock_caption(b).is_empty());
        }
    }
}
